version: '3'

# services:
#   ordenes-db-dev:
#     container_name: ordenes-db-dev
#     image: postgres:16.2
#     restart: always
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: ordenes

services:
  chat-angular:
    container_name: thomia-app
    image: thomia-app
    ports:
      - 80:80
    environment:
      backendApi : 'http://localhost:3000/gpt'
      assinstantApi : 'http://localhost:3000/thom-assistant'
      